<?php
/**
 * Places markup inside already-rendered checkout blocks.
 *
 * @package CheckoutBuilder
 */

declare( strict_types=1 );

namespace CheckoutBuilder\Blocks;

defined( 'ABSPATH' ) || exit;

/**
 * Finds a WooCommerce checkout inner block in rendered HTML and splices markup
 * into it.
 *
 * The block checkout renders its saved inner blocks as a tree of empty
 * `<div data-block-name="…">` placeholders which the client-side app fills in,
 * in DOM order. That makes the rendered page the only place a plugin can decide
 * *where* one of its own blocks appears without the merchant editing the
 * checkout page — so the wrappers are spliced in here.
 *
 * Nothing about this is a general HTML parser: it looks for one exact attribute
 * string and counts `<div>` depth from there. That is enough because the markup
 * it operates on is generated by WooCommerce's own block templates, which emit
 * nothing but nested divs, and because a target that cannot be found is a
 * reported miss rather than a wrong guess.
 */
final class HtmlInjector {

	/**
	 * Whether a block's wrapper appears in the markup.
	 *
	 * @param string $html       Rendered HTML.
	 * @param string $block_name Block name, e.g. woocommerce/checkout-payment-block.
	 * @return bool
	 */
	public static function has_block( string $html, string $block_name ): bool {
		return null !== self::locate( $html, $block_name );
	}

	/**
	 * Insert markup as the last child of a block.
	 *
	 * @param string $html       Rendered HTML.
	 * @param string $block_name Block name.
	 * @param string $markup     Markup to insert.
	 * @return string|null The new HTML, or null when the block is not there.
	 */
	public static function append_inside( string $html, string $block_name, string $markup ): ?string {
		$found = self::locate( $html, $block_name );
		if ( null === $found ) {
			return null;
		}

		return substr( $html, 0, $found['content_end'] ) . $markup . substr( $html, $found['content_end'] );
	}

	/**
	 * Insert markup as the first child of a block.
	 *
	 * @param string $html       Rendered HTML.
	 * @param string $block_name Block name.
	 * @param string $markup     Markup to insert.
	 * @return string|null The new HTML, or null when the block is not there.
	 */
	public static function prepend_inside( string $html, string $block_name, string $markup ): ?string {
		$found = self::locate( $html, $block_name );
		if ( null === $found ) {
			return null;
		}

		return substr( $html, 0, $found['content_start'] ) . $markup . substr( $html, $found['content_start'] );
	}

	/**
	 * Insert markup immediately before a block's opening tag.
	 *
	 * @param string $html       Rendered HTML.
	 * @param string $block_name Block name.
	 * @param string $markup     Markup to insert.
	 * @return string|null The new HTML, or null when the block is not there.
	 */
	public static function insert_before( string $html, string $block_name, string $markup ): ?string {
		$found = self::locate( $html, $block_name );
		if ( null === $found ) {
			return null;
		}

		return substr( $html, 0, $found['start'] ) . $markup . substr( $html, $found['start'] );
	}

	/**
	 * Insert markup immediately after a block's closing tag.
	 *
	 * @param string $html       Rendered HTML.
	 * @param string $block_name Block name.
	 * @param string $markup     Markup to insert.
	 * @return string|null The new HTML, or null when the block is not there.
	 */
	public static function insert_after( string $html, string $block_name, string $markup ): ?string {
		$found = self::locate( $html, $block_name );
		if ( null === $found ) {
			return null;
		}

		return substr( $html, 0, $found['end'] ) . $markup . substr( $html, $found['end'] );
	}

	/**
	 * Take a block's whole element out of the markup.
	 *
	 * The checkout mounts a component for every `data-block-name` wrapper it
	 * finds, so removing the wrapper is how a block that is not a *forced* one —
	 * the order-note box, the coupon form — stops appearing, without the
	 * merchant having to edit their checkout page and without touching the
	 * settings those blocks are otherwise controlled by.
	 *
	 * @param string $html       Rendered HTML.
	 * @param string $block_name Block name.
	 * @return string|null The new HTML, or null when the block is not there.
	 */
	public static function remove_block( string $html, string $block_name ): ?string {
		$found = self::locate( $html, $block_name );
		if ( null === $found ) {
			return null;
		}

		return substr( $html, 0, $found['start'] ) . substr( $html, $found['end'] );
	}

	/**
	 * Find one block's opening tag and its matching close.
	 *
	 * @param string $html       Rendered HTML.
	 * @param string $block_name Block name.
	 * @return array{start: int, content_start: int, content_end: int, end: int}|null
	 */
	private static function locate( string $html, string $block_name ): ?array {
		$offset = 0;

		while ( true ) {
			$attribute = self::attribute_position( $html, $block_name, $offset );
			if ( null === $attribute ) {
				return null;
			}

			$offset    = $attribute + 1;
			$tag_start = strrpos( substr( $html, 0, $attribute ), '<' );

			if ( false === $tag_start || 0 !== strpos( strtolower( substr( $html, $tag_start, 4 ) ), '<div' ) ) {
				continue;
			}

			$tag_end = strpos( $html, '>', $attribute );
			if ( false === $tag_end ) {
				return null;
			}

			$close = self::matching_close( $html, $tag_end + 1 );
			if ( null === $close ) {
				return null;
			}

			return array(
				'start'         => $tag_start,
				'content_start' => $tag_end + 1,
				'content_end'   => $close,
				'end'           => $close + strlen( '</div>' ),
			);
		}//end while
	}

	/**
	 * Where a block's `data-block-name` attribute starts, in either quoting style.
	 *
	 * @param string $html       Rendered HTML.
	 * @param string $block_name Block name.
	 * @param int    $offset     Where to start looking.
	 * @return int|null
	 */
	private static function attribute_position( string $html, string $block_name, int $offset ): ?int {
		$positions = array();

		foreach ( array( '"', "'" ) as $quote ) {
			$at = strpos( $html, 'data-block-name=' . $quote . $block_name . $quote, $offset );
			if ( false !== $at ) {
				$positions[] = $at;
			}
		}

		return array() === $positions ? null : min( $positions );
	}

	/**
	 * Walk forward from inside a div to the `</div>` that closes it.
	 *
	 * @param string $html Rendered HTML.
	 * @param int    $from Offset just past the opening tag.
	 * @return int|null Offset of the closing tag, or null when there is none.
	 */
	private static function matching_close( string $html, int $from ): ?int {
		$depth  = 1;
		$offset = $from;

		while ( preg_match( '~<(/?)div(?=[\s/>])[^>]*>~i', $html, $matches, PREG_OFFSET_CAPTURE, $offset ) ) {
			$at     = (int) $matches[0][1];
			$length = strlen( (string) $matches[0][0] );

			if ( '/' === $matches[1][0] ) {
				--$depth;
				if ( 0 === $depth ) {
					return $at;
				}
			} elseif ( '/>' !== substr( (string) $matches[0][0], -2 ) ) {
				++$depth;
			}

			$offset = $at + $length;
		}

		return null;
	}
}
